pj_cms/urls.py
from django.contrib import admin
from django.db.models.deletion import DO_NOTHING
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from pjarticles.views import login as login_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('pjarticles.urls')),
    path('accounts/login/', login_page),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pjarticles/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'pjarticles'

urlpatterns = [
    path('main/', views.main_view),
    path('login/', views.login),
    path('logout/', views.logout_view),
    path('article/<int:a_id>/', views.article_view),
    path('article_edit/<int:a_id>/', views.article_edit),
    path('article_del/<int:a_id>/', views.article_del, name='article_del'),
    path('article_pub/<int:article_id>/', views.article_pub, name='article_pub'),
    path('article_accept/', views.article_acc),
    path('add_article/', views.add_article),
    path('add_comment/<int:article_id>/', views.add_comment),
    path('contact/', views.contact),
]

templates/add_article.html
{% extends "index.html" %}


{% block articles-imp %}
<div class="col-sm-12"><a href="/articles/logout/">Wyloguj</a></div>
<div class="article">
   <form action="" method="POST" class="" id=""> 
       <div class="col-sm-12" forms>
           {% csrf_token %}
           {{form}}
       </div>
       <div class='ol-sm-6'><button type="submit" class="btn btn-success">Zapisz</button></div>
   </form>

</div>
{% endblock %}

templates/add_comment.html
{% extends "index.html" %}


{% block articles-imp %}
<div class="article">
   <form action="/articles/add_comment/{{art.id}}/" method="POST" class="" id=""> 
       <div class="col-sm-12" forms>
           {% csrf_token %}
           {{form}}
       </div>
       <div class='ol-sm-6'><button type="submit" class="btn btn-success">Zapisz</button></div>
   </form>

</div>
{% endblock %}

templates/article.html
{% extends "index.html" %}
{% load static %}

{% block articles-imp %}
<div class="article"><!--  Artykul -->
    <hr>
    <h2><a href="article.html">{{art.title}}</a></h2>
    <div class="article-info">
        Opublikowano : {{art.pub_data}}
    </div>
    <img src="{% if art.image %}{{art.image.url}}{% else %} # {% endif %}" class="article-img img-rounded">
    <div class="article-intro">
        <p>{{art.content}}</p>
    </div>
    <hr>
    <a href="/articles/add_comment/{{art.id}}/">Dodaj komentarz</a>
    
    <hr>
    {% if adcom.count > 0 %}
    {% for c in adcom %}
    <h4>{{c.user}}</h4>
    <div class="article-info">
        Opublikowano : {{c.pub_data}}
    </div>

    <div class="article-intro">
        <p> Komentarz: {{c.comment}}</p>
    </div>
    
    {% endfor %}
    {% else %}
    <p>Nie ma komenatrzy</p>
    {% endif %}

</div><!-- Koniec artykulu -->
{% endblock %}

templates/article_accept.html
{% extends "index.html" %}
{% load static %}

{% block articles-imp %}
<div class="article">
    <table class="table" id="table" class="display" style="width:100%">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="no-sort first-col"><input type="checkbox" id="all_checkbox" name="active"></th>
                <th scope="col">Tytuł</th>
                <th scope="col">Opis</th>
                <th scope="col">Data publikacji</th>
                <th scope="col" class="td-center no-sort">Czy ważny?</th>
                <th scope="col" class="td-center no-sort">Status</th>
                <th scope="col" class="td-center no-sort">Akceptuj</th>
                <th scope="col" class="td-center no-sort">Usuń</th>
            </tr>
        </thead>
        <tbody>
{% if art.count > 0 %}
{% for art in art %}
            <tr>
                <td><input type="checkbox" class="checkbox" id="{{art.id}}"></td>
                <td>{{art.title}}</td>
                <td>{{art.pub_data}}</td>
                <td>{{art.description}}</td>
                <td>{% if art.important == 1 %}<input type="checkbox" class="" value="T" id="{{art.id}}" checked disabled="True">
                {% else %}
                <input type="checkbox" class="" value="N" id="{{art.id}}"  disabled="True">
                {% endif %}
                </td>
                <td>{% if art.status == 1 %}<input type="checkbox" class="" value="T" id="{{art.id}}" checked disabled="True">
                    {% else %}
                    <input type="checkbox" class="" value="N" id="{{art.id}}"  disabled="True">
                    {% endif %}
                </td>
                <td class ="submit"><form action="{% url 'pjarticles:article_pub' art.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn remove-button" onclick="return confirm('Czy na pewno chcesz publikować artykuł {{art.title}}?');">
                        <i class="fas fa-play"></i>
                    </button>
                    </form>
                </td>
                <td class="delete"> <form action="{% url 'pjarticles:article_del' art.id %}" method="post">
                    {% csrf_token %}
                    <button type="delete" class="btn remove-button" onclick="return confirm('Czy na pewno chcesz usunąć artykuł {{art.title}}?');">
                        <i class="fas fa-trash"></i>
                    </button>
                    </form>
                </td>
            </tr>
{% endfor %}
        </tbody>
    </table>
 <p></p>   
 <div class="card-body">
    <button id= "delete-button" class="btn btn-danger btn-sm disabled" onclick="return confirm('Czy na pewno chcesz usunąć wybrane pozycje')" >Usuń zaznaczone</button>
 </div>
 <p></p>
 <div class="card-body">
    <button id="submit-button" class="btn btn-success" onclick="return confirm('Czy na pewno opublikować wybrane artykuły?')" >Opublikuj zaznaczone</button>
 </div>
 
</div>
{% else %}
    <p>Brak artykułów</p>
{% endif %}

{% endblock %}

templates/article_editor.html
{% extends "index.html" %}


{% block articles-imp %}
<div class="col-sm-12"><a href="/articles/logout/">Wyloguj</a></div>
<div class="article">
   <form action="" method="POST" class="" id=""> 
       <div class="col-sm-12" forms>
           {% csrf_token %}
           {{form}}
       </div>
       <div class='ol-sm-6'><button type="submit" class="btn btn-success">Zapisz</button></div>
   </form>

</div>
{% endblock %}

templates/articles.html
{% extends "index.html" %}
{% load static %}

{% block latest-art %}

{% if error %}
<div>
    <p>{{ error }}</p>
</div>
{% endif %}

{% if art_last.count > 0 %}
{% for article in art_last %}
    <div class="span3 latest-article">
        <div class="latest-article-wrap">
            <h3><a href="/articles/article/{{article.id}}/">{{article.title}}</a></h3>
            {% if request.user.is_authenticated %}
            <a href="/articles/article_edit/{{article.id}}/">Edytuj</a> | <a href="/articles/article_del/{{article.id}}/">Usuń</a>
            {% endif %}
            <div class="article-info">
                Opublikowano : {{article.pub_data}}
            </div>
            <a href="#"><img src="{% static 'img/python-django.png' %}" class="img-rounded"></a>
            <p>{{article.content  |  truncatewords:5}}</p>
            <a href="/articles/article/{{article.id}}" class="label label-info pull-right" target="_blank">Więcej</a>
        </div>
    </div>
{% endfor %}
{% else %}
    <p>Brak artykułów!</p>
{% endif %}

{% endblock %}



{% block articles-imp %}

{% if art.count > 0 %}
{% for art in art %}
<div class="article"><!--  Artykul -->
    <hr>
    <h2><a href="/articles/article/{{art.id}}/">{{art.title}}</a></h2>
    {% if request.user.is_authenticated %}
    <a href="/articles/article_edit/{{art.id}}/">Edytuj</a> | <a href="/articles/article_del/{{art.id}}/">Usuń</a>
    {% endif %}
    <div class="article-info">
        Opublikowano : {{art.pub_data}}
    </div>
    <img src="{% static 'img/python-django.png' %}" class="article-img img-rounded">
    <div class="article-intro">
        <p> {{art.content  |  truncatewords:5}}</p>
    </div>
    <a class="btn btn-inverse art-more" href="/articles/article/{{art.id}}/">Zobacz więcej</a>
</div><!-- Koniec artykulu -->
{% endfor %}
{% else %}
    <p>Brak artykułów</p>
{% endif %}

{% endblock %}

templates/contact.html
{% extends "index.html" %}


{% block articles-imp %}
<div class="article">
    <h2>Masz pytania? Napisz wiadomość!</h2>
   <form action="" method="POST" class="" id=""> 
       <div class="col-sm-12" forms>
           {% csrf_token %}
           {{form}}
       </div>
       <div class='ol-sm-6'><button type="submit" class="btn btn-success">Wyślij</button></div>
   </form>

</div>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <title>Tytuł</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script  src="https://code.jquery.com/jquery-3.6.0.js"  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="  crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css"> 
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
    <script src="https://kit.fontawesome.com/eb0f5d1f2c.js" crossorigin="anonymous"></script>
</head>
 
<body>

<div class="container" id="wrapper">

    <div class="row"><!--  PASEK GORA -->
        <div class="topbar">
            <div class="logo pull-left">
                <h1><a href="#"><img src="{% static 'img/pobrane.png' %}"></a></h1>
            </div>
            <div class="topbar-links pull-right">
                {% if request.user.is_authenticated %}
                <p>User zalogowany: {{ request.user.username }}</p><a href="/articles/logout/">Wyloguj</a> <!-- | <a href="#">Rejestracja</a> -->
                {% else %}
                <p>Brak zalogowanego użytkownika!</p><a href="/articles/login/">Zaloguj</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row"><!-- Menu -->
        <div id="mainmenu" class="navbar navbar-inverse"> 
                <div class="navbar-inner">
                    <div>
                        <a class="brand" href="#">CMS</a>
                        <ul class="nav">
                            <li class="active"><a href="/articles/main/">Główna</a></li>
                            <li><a href="/articles/add_article/">Dodaj Artykuł</a></li>
                            <li><a href="/articles/contact/">Kontakt</a></li>
                            {% if user.is_superuser %}
                            <li><a href="/articles/article_accept/">Zakładka Admin</a></li>
                            {% else %}
                            {{ None }}
                            {% endif %}
                        </ul>
                    </div>
                </div>
        </div>
    </div>

    <div class="row"><!-- Glowna czesc -->

        <div class="span9"><!-- Lewa kolumna -->

            <div  class="row latest"><!-- Najnowsze art -->
                {% block latest-art %}
                {% endblock %}
            </div><!--  Koniec najnowszych art -->

            <div class="row"><!-- Artykuly lista -->
                {% block articles-imp %}
                {% endblock %}
            </div><!--  Koniec listy art -->
            
        </div><!-- Koniec lewej kolumny -->


        <div class="span3"><!-- Prawa kolumna -->
            <div class="well sidebar-nav">
                <h2>Sidebar</h2>
                <h4>Liczba opublikowanych artykułów: {{ status_count }}</h4>
            </div>
        </div>


    </div>

    <div class="row">
        <hr>
        <div class="footer-wrap">
            <p>SWPS @2021</p>
        </div>
    </div>

</div>

</body> 

<script type="text/javascript">
    $(document).ready( function () {
            $('#table').DataTable({"language": {
                    "url": "http://cdn.datatables.net/plug-ins/1.10.21/i18n/Polish.json"}
                });


            $(".table tbody").on('click', 'input:checkbox', function() {
                $(this).closest('tr').toggleClass('selected', this.checked);

                if ($(this).is(":checked")) {
                    var isAllChecked = 0;
                    $(".checkbox").each(function() {
                        if (!this.checked)
                            isAllChecked = 1;
                    })
                    if (isAllChecked == 0) {
                        $("#all_checkbox").prop("checked", true);
                    }

                } else {
                    $("#all_checkbox").prop("checked", false);
                }

            });
        
            $('#all_checkbox').change(function(){
                if (this.checked) {
                    $('.checkbox').each(function() {
                        this.checked = true;
                        $(this).parent().parent().addClass('selected');
                    })
        
                } else  {
                    $('.checkbox').each(function() {
                        this.checked = false;
                        $(this).parent().parent().removeClass('selected')
                    })}
            });
        
            $('#delete-button').click(function(){
                $('.selected .delete form').each(function (){
                    valueToSend = $(this).serialize();
                    $.ajax($(this).attr('action'), {
                        method: $(this).attr('method'),
                        data : valueToSend
                    });
                });
                setTimeout(function(){
                    location.reload(true);
                }, 1500)
            });

            $('#submit-button').click(function(){
                $('.selected .submit form').each(function (){
                    valueToSend = $(this).serialize();
                    $.ajax($(this).attr('action'), {
                        method: $(this).attr('method'),
                        data : valueToSend
                    });
                });
                setTimeout(function(){
                    location.reload(true);
                }, 1500)
            });
            
        });

</script>

</html>

templates/login.html
{% extends "index.html" %}
{% load static %}

{% block articles-imp %}

<div class="col-md-6">
    <h2>Logowanie</h2>

    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-danger">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th>
                    <label for="username">Login</label>
                </th>
                <td>
                    <input type="text" name="username" id="username" required>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="pass">Hasło</label>
                </th>
                <td>
                    <input type="password" name="password" id="password" required>
                </td>
            </tr>
            <tr>
                <th>

                </th>
                <td>
                    <button type="submit" class="btn btn-primary" required>Zaloguj</button>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}